# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bakery_rails_development

test:
  <<: *default
  database: bakery_rails_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # 👈 AJOUTE CETTE LIGNE pour render
  sslmode: require
